language: go
go: 1.x
dist: trusty
os:
  - linux
  - osx
script:
  - bash ./scripts/travis.sh
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - libllvm5.0
      - llvm-5.0-dev
      - clang-5.0
      - libgc-dev
      - cmake
      - time
      - realpath
cache:
  apt: true
  directories:
    - $GOPATH/src/llvm.org/llvm
    - $GOPATH/pkg/linux_amd64/llvm.org/llvm
