language: go
go: 1.x
dist: trusty
os:
  - linux
  - osx
script:
  - bash ./scripts/travis.sh
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - libllvm4.0
      - llvm-4.0-dev
      - clang-4.0
      - cmake
      - time
      - realpath
cache:
  apt: true
  directories:
    - $GOPATH/src/llvm.org/llvm
    - $GOPATH/pkg/linux_amd64/llvm.org/llvm
    - llvm-4.0.0-rc2-workaround
