version: "{build}"
clone_depth: 1
clone_folder: c:\gopath\src\github.com\rhysd\gocaml
environment:
    GOPATH: c:\gopath
install:
    - echo %PATH%
    - echo %GOPATH%
    - go version
    - go env
    - go get -v -t -d ./alpha ./ast ./closure ./gcil ./lexer ./parser ./token ./typing
    - go get golang.org/x/tools/cmd/goyacc
    - go get github.com/haya14busa/goverage
    - set PATH=%PATH%;%GOPATH%\bin
build: off
test_script:
    - goyacc -o parser/grammar.go parser/grammar.go.y
    - goverage -v -coverprofile=cover.out -covermode=count ./alpha ./ast ./gcil ./closure ./lexer ./parser ./token ./typing ./common
after_test:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "cover.out"
deploy: off
